### ISSUE TITLE
Skill incredibly slow

### ISSUE THREAD

**Issue by leonwallis** [dmhacker/alexa-youtube-skill#29]
On average it takes about a minute for the audio to play, which makes the skill barely usable.
I followed [this ](https://www.youtube.com/watch?v=Twz-U0kR2z8)Tutorial, in which it takes a few seconds for the echo to play the audio. My bandwidth is about 10 mbit/s over wifi.

**Comment by dmhacker** [comment]
Hey @leonwallis,

One of the main issues with this skill is that basically, the server downloads whatever YouTube video you are trying to play as a video first and then converts it to audio. This is because Alexa requires a specific bitrate for audio playback. I will be working to download YouTube videos directly as audio with the correct bitrates in the future in order to reduce bandwidth and spend up playback times.

If you think your downloads are slow, I would encourage you to set up your own server using the guide at https://github.com/dmhacker/dmhacker-youtube. Best of luck. 

Referencing #11.
